/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dietmanagement;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import javax.swing.table.*;

/**
 *
 * @author HP
 */
public class Mainform extends javax.swing.JFrame {

    /**
     * Creates new form Mainform
     */
    public Mainform() {
        initComponents();
        MySqlConnection();
        
        //userLabel.setText(usern);
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("dietplan.jpg")));
        Image img1 = myimage.getImage();
       Image img2 = img1.getScaledInstance(imagedashboard.getWidth(),imagedashboard.getHeight(),Image.SCALE_SMOOTH);
        //Image img2 = img1.getScaledInstance(1007, 729 ,Image.SCALE_SMOOTH);
        ImageIcon i= new ImageIcon(img2);
       imagedashboard.setIcon(i);
    }
public void close(){
      WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    Mainform(String usern) {
        initComponents();
        
       userLabel.setText(usern);
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("dietplan.jpg")));
        Image img1 = myimage.getImage();
       Image img2 = img1.getScaledInstance(imagedashboard.getWidth(),imagedashboard.getHeight(),Image.SCALE_SMOOTH);
        //Image img2 = img1.getScaledInstance(1007, 729 ,Image.SCALE_SMOOTH);
        ImageIcon i= new ImageIcon(img2);
       imagedashboard.setIcon(i);
       
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
       public Connection MySqlConnection() {
        Connection con = null;
        try { 
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dietManagement","root","1234");
       //JOptionPane.showMessageDialog(null, "My sql connectivity done");
        return con;
    }
         catch (Exception e)
    {
             
         System.out.println(e);
         //JOptionPane.showMessageDialog(this,"My sql connectivity not done");
    // System.out.println("exception caught");
     return null;
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        imagedashboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        weightgainMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        weightlossMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        account = new javax.swing.JMenu();
        resetmenuitem = new javax.swing.JMenuItem();
        logoutmenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagedashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dietmanagement/dietplan.jpg"))); // NOI18N

        jLabel1.setText("User Name");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 255));

        jMenu1.setText("Weight gain");

        weightgainMenuItem.setText("Diet plan");
        weightgainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightgainMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(weightgainMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Weight loss");

        weightlossMenuItem.setText("Vegge diet");
        weightlossMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightlossMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(weightlossMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Muscles gain");

        jMenuItem4.setText("diet plan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Muscless loss");

        jMenuItem6.setText(" Diet plan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        account.setText("account");
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });

        resetmenuitem.setText("Reset password");
        resetmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetmenuitemActionPerformed(evt);
            }
        });
        account.add(resetmenuitem);

        logoutmenuItem.setText("Logout");
        logoutmenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuItemActionPerformed(evt);
            }
        });
        account.add(logoutmenuItem);

        jMenuBar1.add(account);

        jMenu5.setText("Help");

        jMenuItem1.setText("Contact us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagedashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagedashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightgainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightgainMenuItemActionPerformed
        // TODO add your handling code here:
        // Vegge gain menu diet plan plan 
       // String user = userLabel.getText().trim();
        new  WeightGain().setVisible(true);
        /*DefaultTableModel model = (DefaultTableModel) table.getModel();
       model.setRowCount(0);
       
        try {
            //Class.forName("java.sql.DriverManager");
            //Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/java_stock", "root", "");
            Connection con = MySqlConnection();
            Statement stmt = con.createStatement();
            String query = "select * from weightgain ";
            java.sql.ResultSet rs=stmt.executeQuery(query);

            while(rs.next()) {
                String id = rs.getString("day");
                String name = rs.getString("breakfast");
               
                String qun =rs.getString("morningsnack");
                String price = rs.getString("lunch");
                
                String mfd = rs.getString("eveningsnack");
                String exp = rs.getString("dinner");
                //String batchno = rs.getString("batchno");
                
              

               model.addRow(new Object[] {id,name,qun,price,mfd,exp});
            }
            rs.close();
            //stmt.close();
            //con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }*/
    }//GEN-LAST:event_weightgainMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new  Musclesgain().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(this,"Logout click event ");
//         dispose();
//         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//         system.out.println("click event logout");
    }//GEN-LAST:event_accountActionPerformed

    private void resetmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetmenuitemActionPerformed
        // TODO add your handling code here:
         String user = userLabel.getText().trim();
        new  ResetPassword(user).setVisible(true);
    }//GEN-LAST:event_resetmenuitemActionPerformed

    private void logoutmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuItemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_logoutmenuItemActionPerformed

    private void weightlossMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightlossMenuItemActionPerformed
        // TODO add your handling code here:
         new  Weightloss().setVisible(true);
    }//GEN-LAST:event_weightlossMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Contactus().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu account;
    private javax.swing.JLabel imagedashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuItem logoutmenuItem;
    private javax.swing.JMenuItem resetmenuitem;
    private javax.swing.JLabel userLabel;
    private javax.swing.JMenuItem weightgainMenuItem;
    private javax.swing.JMenuItem weightlossMenuItem;
    // End of variables declaration//GEN-END:variables

    private String getText(JTextField nameTextField) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
